import type { ProposePatchOperation } from '@synthesize/shared-types';
import type { ApprovalResult, ApplyResult, ProposalSource, ProposalUiState, RollbackResult, ValidationResult } from '../../app/App';
import type { AgentProfileId } from '../agentProfiles/AgentPanel';

export function DiffQueue(props: {
  patches: ProposePatchOperation[];
  validationByProposal: ProposalUiState<ValidationResult>;
  approvalByProposal: ProposalUiState<ApprovalResult>;
  applyByProposal: ProposalUiState<ApplyResult>;
  rollbackByProposal: ProposalUiState<RollbackResult>;
  isDirty: boolean;
  agentProfileId: AgentProfileId;
  proposalSourceByProposal: Record<string, ProposalSource | undefined>;
  onValidate: (operation: ProposePatchOperation) => void;
  onApprove: (operation: ProposePatchOperation) => void;
  onApply: (operation: ProposePatchOperation) => void;
  onRollback: (operation: ProposePatchOperation) => void;
}) {
  return (
    <div className="panel">
      <h3>Diff Queue</h3>
      {props.patches.length === 0 ? (
        <div className="diffitem">
          <strong>No pending patches</strong>
          <div className="small">Agent patches require backend snapshotting, validation, approval, checkpointed apply, audit, and rollback support.</div>
        </div>
      ) : props.patches.map((patch) => {
        const validationForPatch = props.validationByProposal[patch.proposalId] ?? null;
        const approvalForPatch = props.approvalByProposal[patch.proposalId] ?? null;
        const applyForPatch = props.applyByProposal[patch.proposalId] ?? null;
        const rollbackForPatch = props.rollbackByProposal[patch.proposalId] ?? null;
        const isValidated = validationForPatch?.ok === true;
        const isApproved = isValidated && !!approvalForPatch && approvalForPatch.operation_sha256 === validationForPatch?.operation_sha256;
        const isApplied = !!applyForPatch && !rollbackForPatch;
        const isRolledBack = !!rollbackForPatch;
        const source = props.proposalSourceByProposal[patch.proposalId];
        const sourceAgentProfileId = source?.agentProfileId ?? props.agentProfileId;
        const hasPersistedContext = !!source?.contextBundleId;
        const canValidateProfile = hasPersistedContext && (sourceAgentProfileId === 'local-patcher' || sourceAgentProfileId === 'fake-demo');
        const canApply = isApproved && !isApplied && !isRolledBack && !props.isDirty;
        const canRollback = isApplied && !isRolledBack && !props.isDirty;
        return (
          <div className="diffitem" key={patch.proposalId}>
            <strong>{patch.summary}</strong>
            <div className="small">Proposal: {patch.proposalId}</div>
            <div className="small">Source agent: {sourceAgentProfileId}{source?.contextBundleId ? ` · context ${source.contextBundleId}` : ''}</div>
            <div className="small">Current commit: {patch.currentCommit || 'none / non-git fixture'}</div>
            {patch.riskNotes.map((note) => <div className="small" key={note}>Risk note: {note}</div>)}
            {patch.files.map((file) => (
              <details key={file.id} open>
                <summary>{file.path} · {file.id}</summary>
                <div className="small">{diffStats(file.patch)}</div>
                <div className="small">beforeSha256: {file.beforeSha256}</div>
                <pre className="diffpre">{file.patch}</pre>
              </details>
            ))}

            {patch.suggestedCommands.length > 0 && (
              <details open>
                <summary>Suggested commands — classification only</summary>
                {patch.suggestedCommands.map((cmd, idx) => (
                  <div className="small" key={`${patch.proposalId}-cmd-${idx}`}>
                    <code>{cmd.argv.join(' ')}</code> · cwd {cmd.cwd} · requiresNetwork={String(cmd.requiresNetwork)} · mayModifyFiles={String(cmd.mayModifyFiles)} · execution disabled
                  </div>
                ))}
              </details>
            )}
            <div className="notice error"><strong>Repo safety warning</strong><div className="small">Use a clean Git branch or throwaway repo. Synthesize checkpoints changes, but this is not a substitute for version control.</div></div>
            {!hasPersistedContext && <div className="notice error"><strong>Missing persisted context binding</strong><div className="small">Synthesize requires every patch proposal to be bound to the backend-owned context bundle that generated it. Ask the local agent again before validation.</div></div>}
            {hasPersistedContext && !canValidateProfile && <div className="notice error"><strong>Agent profile is not patch-enabled</strong><div className="small">This proposal was generated by {sourceAgentProfileId}, which is report/review oriented. Switch to Local Patcher and ask again to create a patch-capable proposal.</div></div>}
            <div className="buttonrow">
              <button className="primary" disabled={!canValidateProfile} onClick={() => props.onValidate(patch)}>Validate + snapshot in backend</button>
              <button className="primary" disabled={!isValidated || !!approvalForPatch || props.isDirty} onClick={() => props.onApprove(patch)}>Approve persisted proposal</button>
              <button className="primary" disabled={!canApply} onClick={() => props.onApply(patch)}>Apply approved snapshot</button>
              <button disabled={!canRollback} onClick={() => props.onRollback(patch)}>Rollback via backend proposal</button>
            </div>
            {props.isDirty && <div className="notice error"><strong>Dirty buffer</strong><div className="small">Apply is disabled until the target file is refreshed/clean. Backend apply targets disk state.</div></div>}
            {validationForPatch && (
              <div className={validationForPatch.ok ? 'notice ok' : 'notice error'}>
                <strong>{validationForPatch.ok ? 'Validated and persisted' : 'Rejected'}</strong>
                <div className="small">Status: {validationForPatch.status}</div>
                <div className="small">Operation hash: {validationForPatch.operation_sha256}</div>
                <div className="small">{validationForPatch.message}</div>
                {validationForPatch.files.map((file) => (
                  <div className="small" key={file.id}>{file.path}: risk {file.risk}</div>
                ))}
              </div>
            )}
            {approvalForPatch && (
              <div className="notice ok">
                <strong>Approved by backend</strong>
                <div className="small">Approval: {approvalForPatch.approval_id}</div>
                <div className="small">Approved by: {approvalForPatch.approved_by_source}</div>
                <div className="small">Operation hash: {approvalForPatch.operation_sha256}</div>
              </div>
            )}
            {isApplied && applyForPatch && (
              <div className="notice ok">
                <strong>Applied from persisted snapshot</strong>
                <div className="small">Checkpoint: {applyForPatch.checkpoint_id}</div>
                <div className="small">Checkpoint id is display-only; rollback loads checkpoint by proposal id</div>
                {applyForPatch.applied_files.map((file) => (
                  <div className="small" key={file.id}>{file.path}: {file.after_sha256}</div>
                ))}
              </div>
            )}
            {rollbackForPatch && (
              <div className="notice ok">
                <strong>Rolled back</strong>
                <div className="small">Restored: {rollbackForPatch.restored_paths.join(', ') || 'none'}</div>
                <div className="small">Deleted created files: {rollbackForPatch.deleted_paths.join(', ') || 'none'}</div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}


function diffStats(diff: string): string {
  let additions = 0;
  let deletions = 0;
  for (const line of diff.split('\n')) {
    if (line.startsWith('+++') || line.startsWith('---')) continue;
    if (line.startsWith('+')) additions += 1;
    if (line.startsWith('-')) deletions += 1;
  }
  return `${additions} additions, ${deletions} deletions`;
}
